name: nsu_2026capstone
channels:
  - conda-forge
  - defaults
dependencies:
  - aom=3.6.0=h313beb8_0
  - appnope=0.1.4=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - blas=1.0=openblas
  - bzip2=1.0.8=h80987f9_6
  - c-ares=1.34.5=h2ca31fc_0
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cairo=1.18.4=h191e429_0
  - comm=0.2.3=pyhe01879c_0
  - cyrus-sasl=2.1.28=h0121217_3
  - dav1d=1.2.1=h80987f9_0
  - debugpy=1.8.16=py310h0962b89_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - eigen=3.4.0=h48ca7d4_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.1=h313beb8_0
  - ffmpeg=6.1.1=h7693a39_3
  - fontconfig=2.15.0=h29935d0_0
  - freetype=2.13.3=h47d26ad_0
  - fribidi=1.0.10=h1a28f6b_0
  - gdk-pixbuf=2.42.10=h969f7ef_2
  - gettext=0.21.0=hbdbcc25_2
  - gflags=2.2.2=h313beb8_1
  - giflib=5.2.2=h80987f9_0
  - glib=2.84.4=h863a760_0
  - glib-tools=2.84.4=hff4a405_0
  - glog=0.5.0=h313beb8_1
  - graphite2=1.3.14=hc377ac9_1
  - gst-plugins-base=1.24.12=hc962c03_1
  - gstreamer=1.24.12=h4a1bc71_1
  - gstreamer-orc=0.4.41=hdbbdb2f_0
  - harfbuzz=10.2.0=he637ebf_1
  - hdf5=1.14.5=hd77251f_2
  - icu=73.1=h313beb8_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=7.1.0=pyh5552912_0
  - ipython=8.37.0=pyh8f84b5b_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jpeg=9f=h2f69dba_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - krb5=1.21.3=h237132a_0
  - lame=3.100=h1a28f6b_0
  - lcms2=2.16=he26ebf3_1
  - leptonica=1.82.0=hdedf53e_3
  - lerc=4.0.0=h313beb8_0
  - libabseil=20250127.0=cxx17_h313beb8_0
  - libarchive=3.8.2=ha845c4f_0
  - libavif=1.1.1=h80987f9_0
  - libcurl=8.16.0=h01d3526_0
  - libcxx=20.1.8=hd7fd590_1
  - libdeflate=1.22=h80987f9_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libev=4.33=h1a28f6b_1
  - libevent=2.1.12=h02f6b3c_1
  - libffi=3.4.4=hca03da5_1
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libglib=2.84.4=h7a3292d_0
  - libiconv=1.16=h80987f9_3
  - libidn2=2.3.8=h9681e36_0
  - libkrb5=1.21.3=h73ed823_4
  - libnghttp2=1.57.0=h62f6fdd_0
  - libogg=1.3.5=h1a28f6b_1
  - libopenblas=0.3.30=hf2bb037_0
  - libopenjpeg=2.5.4=haa24f5a_1
  - libopus=1.3.1=h80987f9_1
  - libpng=1.6.50=h5c318fc_0
  - libpq=17.6=h479fd88_0
  - libprotobuf=5.29.3=h14f15fd_1
  - librsvg=2.56.3=h38920c8_2
  - libsodium=1.0.20=h897f8a9_0
  - libssh2=1.11.1=h3e2b118_0
  - libtheora=1.1.1=h1a28f6b_3
  - libtiff=4.7.0=h91aec0a_0
  - libunistring=1.3=h1799b2a_0
  - libvorbis=1.3.7=h1a28f6b_0
  - libvpx=1.13.1=h313beb8_0
  - libwebp=1.3.2=hf40cdb4_1
  - libwebp-base=1.3.2=h80987f9_1
  - libxml2=2.13.9=h528a072_0
  - libzlib=1.3.1=h5f15de7_0
  - llvm-openmp=20.1.8=he822017_0
  - lmdb=0.9.31=h79febb2_0
  - lz4-c=1.9.4=h313beb8_1
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mysql-common=9.3.0=h0968ce5_3
  - mysql-libs=9.3.0=ha948bd4_3
  - ncurses=6.5=hee39554_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - opencv=4.12.0=py310h73087f0_0
  - openh264=2.1.1=h98b2900_0
  - openjpeg=2.5.4=h959fc53_1
  - openldap=2.6.10=h6d5b105_1
  - openssl=3.5.4=h5503f6c_0
  - packaging=25.0=pyh29332c3_1
  - pango=1.50.7=hf2328af_2
  - parso=0.8.5=pyhcf101f3_0
  - pcre2=10.46=h1dacb4a_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.2=pyhc872135_1
  - pixman=0.46.4=h09dc60e_0
  - platformdirs=4.5.0=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.0.0=py310haa24f5a_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.10.19=hf701271_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - pyzmq=27.1.0=py310h854a7ef_0
  - qtbase=6.9.2=hcf95447_4
  - readline=8.3=h0b18652_0
  - setuptools=80.9.0=py310hca03da5_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.50.2=h79febb2_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tesseract=5.2.0=h9e66425_3
  - tk=8.6.15=hcd8a7d5_0
  - tornado=6.5.1=py310h80987f9_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h04d1e81_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=py310hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zeromq=4.3.5=h888dc83_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=h5f15de7_0
  - zstd=1.5.7=h817c040_0
  - pip:
      - absl-py==2.3.1
      - attrs==25.4.0
      - cffi==2.0.0
      - contourpy==1.3.2
      - cycler==0.12.1
      - flatbuffers==25.9.23
      - fonttools==4.60.1
      - jax==0.6.2
      - jaxlib==0.6.2
      - kiwisolver==1.4.9
      - matplotlib==3.10.7
      - mediapipe==0.10.21
      - ml-dtypes==0.5.3
      - numpy==1.26.4
      - opencv-contrib-python==4.11.0.86
      - opt-einsum==3.4.0
      - pillow==12.0.0
      - protobuf==4.25.8
      - pycparser==2.23
      - pyparsing==3.2.5
      - pyserial==3.5
      - scipy==1.15.3
      - sentencepiece==0.2.1
      - sounddevice==0.5.3
